### ISSUE TITLE
Communication?

### ISSUE THREAD

**Issue by stevestreza** [mattgemmell/MGTwitterEngine#1]
Current collaborators are myself, mattgemmell, aral, ctshryock, and MrRooni. Should we just use GitHub issues for now?

**Comment by stevestreza** [comment]
AFAIK there's no GitHub UI for the list of collaborators added to a project, but there is an API call you can make with `curl http://github.com/api/v2/json/repos/show/mattgemmell/MGTwitterEngine/collaborators` to get a JSON list back.

**Comment by stevestreza** [comment]
Welcome on board, alexrepty!

**Comment by alexrepty** [comment]
Thanks :)

**Comment by tarasis** [comment]
Not sure were best to put this (raise an Issue about lack of Cursor support?) but I have some changes which add support for cursors, will post to my branch soon and you can merge those if you want.

**Comment by alexrepty** [comment]
Robert, just send a pull request with your changes and we'll see about merging.

**Comment by catsby** [comment]
This morning I merged tarasis's branch with mine and alexrepty's into my fork.  I then cloned the root project and merged my fork into it and everything applied cleanly, so, should/can I just push an update to mattgemmell/MGTwitterEngine or do I send a pull request?  Since I'm a contributor I can just push but I didn't know if we wanted to do some review prior?

**Comment by stevestreza** [comment]
I posted a comment about creating an MGTwitterEngineCursorID for the cursor-based methods. Other than that, the commits look good to me.

**Comment by tarasis** [comment]
I've push commit http://github.com/tarasis/MGTwitterEngine/commit/bd8ec01fdd09a3724f06f807e15b7f7dd48707b4 for the MGTwitterEngineCursorID

**Comment by stevestreza** [comment]
Looks good.

**Comment by catsby** [comment]
I pulled the latest commit from tarasis into my fork and resolved a conflict in MGTwitterEngineGlobalHeader.h.  Unless anyone has any objections I'll update mattgemmell/MGTwitterEngine at EOB central (2.5 some hours...)

**Comment by tarasis** [comment]
I'm going to go through the rest of the API as currently implemented and add Cursors & remove Pages where appropriate. I'll commit after you've done the merge.

**Comment by catsby** [comment]
I just updated mattgemmell/MGTwitterEngine with tarasis's, alexrepty, and my own fork.

**Comment by stevestreza** [comment]
I'm closing this ticket as it's gone way off track and everyone seems fine with using the issue tracker for communication for now.

**Comment by tarasis** [comment]
Certainly I'm happy using it, probably worth using the Wiki to note what we are working on. Yes we can merge whatever from whoevers branch but a rough list could avoid duplicated effort.
