### ISSUE TITLE
Convert libxml and yajl code to use TouchXML/TouchJSON

### ISSUE THREAD

**Issue by stevestreza** [mattgemmell/MGTwitterEngine#10]
The TouchXML and TouchJSON codebases have nice fire-and-forget APIs which create object trees for the document (TouchXML returns an API like NSXMLDocument, and TouchJSON returns native NSArray/NSDictionary objects). These will be much less error-prone for the engine to use, and will require much less code to send to delegates.

**Comment by stevestreza** [comment]
Opened up a branch for implementing TouchJSON support. http://github.com/mattgemmell/MGTwitterEngine/tree/touchjson

**Comment by stevestreza** [comment]
Added TouchJSON support, seems to be working for most GET requests. mattgemmell/MGTwitterEngine@051b6b6cf2a9387f5e516f9581e62d3e1bd02e84

**Comment by stevestreza** [comment]
In my own apps, I needed to tweak a couple of the delegate implementations, but otherwise TouchJSON was a very simple drop-in replacement for the YAJL parsers.

**Comment by justin** [comment]
How does touchjson compare to yajl in terms of performance & memory usage?

**Comment by stevestreza** [comment]
I haven't done performance testing on it yet; I'll hit it later tonight on an iPhone.

The motivation behind this came while implementing support for Twitter lists. When accessing the GET /:user/lists API endpoint, the stock YAJL parser would not return the data ordered correctly. Specifically, instead of returning the list's `description` field, it would instead return the `description` of the user who owned the list. My quick TouchJSON implementation handles this correctly.

**Comment by stevestreza** [comment]
TouchJSON has been merged into master.
