### ISSUE TITLE
MGTwitterEngine for armv7s

### ISSUE THREAD

**Issue by sujithkris** [mattgemmell/MGTwitterEngine#108]
MGTwitterEngine is giving error when compiling for armv7s architecture.

Please recompile with armv7s support and release the library.

**Comment by mattgemmell** [comment]
This is still open-source, right? Why don't you fix it?

**Comment by sujithkris** [comment]
I downloaded the code from https://github.com/mattgemmell/MGTwitterEngine
By default, the architectures are for Mac. Am I downloading the right content ?

**Comment by catsby** [comment]
Please follow the wiki https://github.com/mattgemmell/MGTwitterEngine/wiki/Building-and-testing-MGTwitterEngine

**Comment by catsby** [comment]
Closing
