### ISSUE TITLE
YAJL parser no longer deals with search results properly 

### ISSUE THREAD

**Issue by ghost** [mattgemmell/MGTwitterEngine#12]
Since April 1st (maybe this is all a bad joke), MGTwitterEngine isn't dealing with my search results properly.

Suspect it is related to this: http://groups.google.com/group/twitter-api-announce/browse_thread/thread/983086ae9935d50c, as search results are now delimited by the new 'metadata' dictionary that is in the search results: consequently some fields for a status are returned separately from others:

```
search: dictionary start = (null)
search:   results: profile_image_url = http://a1.twimg.com/profile_images/759588518/Picture0007_normal.jpg (NSCFString)
search:   results: created_at = 1270227708 (NSCFNumber)
search:   results: from_user = BieberIsOurDrug (NSCFString)
search: dictionary start = metadata
search:   results: result_type = recent (NSCFString)
search: dictionary end
search:   status: to_user_id = <null> (NSNull)
search:   status: text = Hahaha ! I didn't know @justinbieber said "bitch" in the thing for Bieber Or Die (NSCFString)
search:   status: id = 11490430212 (NSCFNumber)
search:   status: from_user_id = 98209887 (NSCFNumber)
search:   status: geo = <null> (NSNull)
search:   status: iso_language_code = en (NSCFString)
search:   status: source = <a href="/devices" rel="nofollow">txt</a> (NSCFString)
search: dictionary end
```

In the above, the section before the metadata ends up split off from the one after it when returned in `searchResultsReceived:forRequest:`, despite it being from the same status.

**Comment by ghost** [comment]
I've created a work-around for metadata for myself, but I think changes need to be made so that nested dictionaries do not break the parser.

The work-around is:

miketomasello/MGTwitterEngine@89728452617611098f4940f689542df226c5c88a

**Comment by alexrepty** [comment]
I've merged this into master. Thanks!

**Comment by deepp** [comment]
millions n millions of thanks miketomasello.....I had been working on it for last 2 days but was not getting it done...Thank you very much

**Comment by ghost** [comment]
I found some other problems so I since rewrote this class. However, while it now works with all types of nested datastructures, the format of datastructure it returns is the same as the actual API uses, rather than the slightly modified datastructure of before. In my own app, I'm content with that, but I suspect it'd be confusing to others.

I'd love to know the reason why MGTwitterEngine changes the datastructures, though.
