### ISSUE TITLE
base64EncodingWithLineLength error

### ISSUE THREAD

**Issue by ghost** [mattgemmell/MGTwitterEngine#13]
While running the library in iPhone 3.1 I get the following error...

**\* -[NSConcreteMutableData base64EncodingWithLineLength:]: unrecognized selector sent to instance 0x3d17e50

...on line...

NSString *authValue = [NSString stringWithFormat:@"Basic %@", [authData base64EncodingWithLineLength:80]];

...of this method...
- (NSMutableURLRequest *)_baseRequestWithMethod:(NSString *)method
  path:(NSString *)path 
  requestType:(MGTwitterRequestType)requestType 
  queryParameters:(NSDictionary *)params 

It should be noted that the same code runs fine in the Simulator.

Any help will be much appreciated.

**Comment by stevestreza** [comment]
`-[NSData base64EncodingWithLineLength:]` is in a category on NSData, defined in NSData+Base64.h. Be sure to include those in your project.

If this is still a problem, check your application's linker flags. Try adding: `-all_load -ObjC`. This should fix the issue.

**Comment by ghost** [comment]
Thanks! It was a linker problem.
