### ISSUE TITLE
EXC_BAD_ACCESS crash with spaces in user name

### ISSUE THREAD

**Issue by richardbuckle** [mattgemmell/MGTwitterEngine#14]
Steps to reproduce:
1  #define TESTING_SECONDARY_USER @"chocken berry" // note space
2  uncomment the line NSLog(@"getUserTimelineFor: connectionIdentifier = %@", [twitterEngine getUserTimelineFor:TESTING_SECONDARY_USER sinceID:0 startingAtPage:0 count:3]);  
3  Observe EXC_BAD_ACCESS crash

I'd settle for at least defined behavior here, even if it's just throwing an exception, but ideally the engine should be robust against such malformed input and fail the request via normal delegate methods. Also, methods to help client programmers validate user input would be helpful here. Thoughts welcomed.

**Comment by ghost** [comment]
I believe I've fixed this, but someone will need to merge it back into MGTwitterEngine.

miketomasello/MGTwitterEngine@40a31cf0f3c320af34270e3db7626dbd64c7f053

**Comment by ghost** [comment]
Merged it into master, hopefully that fixes the problem.
