### ISSUE TITLE
MGTwitterYAJLParser

### ISSUE THREAD

**Issue by evripidis** [mattgemmell/MGTwitterEngine#15]
MGTwitterYAJLParser.h, comes with an error at " #import "yajl_parse.h" "(can't be found) which is normal (there is no such file).

Also MGTwitterYAJLParser.m, comes with an error at :

@interface MGTwitterYAJLParser : NSObject {
    __weak NSObject <MGTwitterParserDelegate> *delegate; // weak ref
    NSString *identifier;
    MGTwitterRequestType requestType;
    MGTwitterResponseType responseType;
    NSURL *URL;
    NSData *json;
    NSMutableArray *parsedObjects;
    MGTwitterEngineDeliveryOptions deliveryOptions;

```
yajl_handle _handle;
```

}

" Expected specifier-qualifier-list before "yajl_handle"

Are there any extra changes to be made after the 1.0.8 version ? (before the Github), cause before that, everything worked fine. 
Thank you for your time

**Comment by stevestreza** [comment]
If you don't have YAJL, you don't need to include the *YAJLParser files in your project. If you do have YAJL, you could try poking in your project's header search paths to search for the YAJL headers.
