### ISSUE TITLE
non-existant NSDate call on iPhone platform

### ISSUE THREAD

**Issue by ghost** [mattgemmell/MGTwitterEngine#17]
this causes compilation to fail with -Werror 

was fixed in 34008709ab145de1bf550de661224ed6ef9da8a3 but reverted by e775488454f94beb730a25f47ab25f14dee3f23c - no reason was given, so I'm not sure whether my own change will meet the criteria that the first fix failed.

iPhone OS not-with-standing, the current way this is done uses dateWithNaturalLanguageString:, which is described on the Apple docs with the following caveat:

> This method supports only a limited set of colloquial phrases, primarily in English. It may give unexpected results, and its use is strongly discouraged.

I have changed this to use NSDateFormatter, as recommended by Apple.

miketomasello/MGTwitterEngine@8bae8f787e6e2b72dee23d08bb6d9b50f14398e5

**Comment by intabulas** [comment]
Wrong format in that commit (at least for me), needs to be EEE MMM dd HH:mm:ss +0000 yyyy

**Comment by stevestreza** [comment]
Fixed in 7568a6147a560f555991364b343adbf55f74ebb8.
