### ISSUE TITLE
retweeted_status support for YAJL and LibXML parsers

### ISSUE THREAD

**Issue by btjones** [mattgemmell/MGTwitterEngine#18]
Currently the YAJL parser and LibXML parser don't have support for retweeted_status nodes within a status node. As a result, when using these parsers, statuses that are retweets don't appear as retweets in the dictionary returned from MGTwitterEngine.

However, the NSXML parser does support it: (commit here: http://github.com/mattgemmell/MGTwitterEngine/commit/2b7339835aee85f27fd43f99691fc0a3fc462027)

**Comment by btjones** [comment]
I rewrote MGTwitterStatusesYAJLParser to be pretty generic so it can handle retweet_statuses. Here is the commit in my fork: http://github.com/btjones/MGTwitterEngine/commit/3725ff4c7f6fe14fc19d384cc130bf36f9f01235

**Comment by ghost** [comment]
I was just thinking about doing this today. I'd merge this in, but why do you convert the keys to camel case? If I'm not mistaken, that'd cause problems with existing code.

Additionally, MGTwitterSearchYAJLParser should probably be updated to accept dictionaries within statuses too.

**Comment by btjones** [comment]
For some reason I got it in my head that camel case was a convention MGTwitterEngine was following. Not sure why though because after looking over the code again there is no camel case used for dictionary keys. I've removed the camel case conversion and recommitted: http://github.com/btjones/MGTwitterEngine/commit/44305184f4c7a9cc7d0fa773b76e4d77b99b63e1

**Comment by btjones** [comment]
Oh, and I agree about the MGTwitterSearchYAJLParser changes that are needed too. If someone else doesn't get around to it I may end up rewriting that too when I get to the search part of the app I'm working on.

**Comment by ghost** [comment]
I merged your changes and also modified MGTwitterSearchYAJLParser to work in the same way. Hopefully everything still works!
