### ISSUE TITLE
Merging changes from amazingsyco/MGTwitterEngine

### ISSUE THREAD

**Issue by stevestreza** [mattgemmell/MGTwitterEngine#2]
My fork of [MGTwitterEngine](http://github.com/amazingsyco/MGTwitterEngine) has some additions to make it easier for subclasses to override the networking layer. I'd like to move these changes into the main trunk. You can see them in the fork queue.

I'm a collaborator so I can do this, but I wouldn't mind a few eyes taking a look at it first.

**Comment by alexrepty** [comment]
Steve,

I looked over the changes and most of it looks great. There were just two issues, which I commented on in your fork.

These two remaining issues aside, I think the changes can be merged.

Cheers,
Alex

**Comment by stevestreza** [comment]
I agree with the two issues, and I'll get those changed.

**Comment by stevestreza** [comment]
Fixed:
- amazingsyco/MGTwitterEngine@8081c2b9dce836acd066100a15c4e4c62586a3fc 
- amazingsyco/MGTwitterEngine@7fe0e3cdafe12b7c78834b7ec7b1ac2b373e4dac

**Comment by alexrepty** [comment]
Great. I didn't see any other issues with the merge, so from my point of view you might just go ahead and apply the changes.

**Comment by alexrepty** [comment]
Ok, I've merged the changes and found some issues with the format specifiers (%u). Fixed those, so master should now be fully functioning.

**Comment by stevestreza** [comment]
Just pulled the changes, commits and works here. Thanks!
