### ISSUE TITLE
Character counting for status updates should use Unicode Normalized Form C

### ISSUE THREAD

**Issue by luciuskwok** [mattgemmell/MGTwitterEngine#21]
The official way to count characters for status updates and other text in Twitter is to use the Unicode Normalized Form C, which is created by -[NSString precomposedStringWithCanonicalMapping]. I have added code to convert the status to the canonical mapping in my fork: http://github.com/luciuskwok/MGTwitterEngine

**Comment by stevestreza** [comment]
Merged into master.
