### ISSUE TITLE
Date with Locale is not working

### ISSUE THREAD

**Issue by ghost** [mattgemmell/MGTwitterEngine#22]
Hi,

In MGTwitterXMLParser.m in parser function the create date "created_at" isn't working in iPhones with dates not in english.

You can avoid this adding a locale to NSDateFormatter

NSDateFormatter *dateFormatter = [[NSDateFormatter alloc] init];
        [dateFormatter setLocale:[[NSLocale alloc] initWithLocaleIdentifier:@"en_US"]]; // ADDED THIS LINE TO AVOID PROBLEMS WITH DATES
        dateFormatter.dateFormat = @"EEE MMM dd HH:mm:ss +0000 yyyy";
        NSDate *creationDate = [dateFormatter dateFromString:[currentNode objectForKey:elementName]];
        [dateFormatter release];
        if (creationDate) {
            [currentNode setObject:creationDate forKey:elementName];
        }

Kind Regards

**Comment by stevestreza** [comment]
Fixed in 12afbd352f579355204762278d05a6ffe2027a03. Thanks!
