### ISSUE TITLE
Bugs in xAuth, retweet and delete when using TouchJSON.

### ISSUE THREAD

**Issue by farnell** [mattgemmell/MGTwitterEngine#27]
There were problems when using TouchJSON

1) Problems getting the token when using getXAuthAccessTokenForUsername. The problem was that the response from the xAuth http://dev.twitter.com/pages/xauth isn't JSON format to the parsing failed when it got the reponse. 

2) There were problems using any method that had an empty POST body. Methods such as retweet, deleteUpdate resulted in signature problems and 401 (authentication) response. 

I've fixed these 2 bugs in 7b572caf3cb504008d1f on lepah/MGTwitterEngine.

**Comment by destari** [comment]
I had this problem too - your change fixed it.  Thanks!

**Comment by farnell** [comment]
no problem, glad it helped

**Comment by stevestreza** [comment]
Closed by 413d1e9cb0be7c370b251fe27f96a09832cf3347. Parses OAuth token manually with TouchJSON enabled
