### ISSUE TITLE
connectionStarted: is not invoked

### ISSUE THREAD

**Issue by wharris** [mattgemmell/MGTwitterEngine#28]
The connectionStarted: delegate method is not invoked on the delegate when a network connection is started.

The connectionStarted: delegate method was added in 561579903415169a04f1 but was broken in 284071147f728cfeb24b.

**Comment by stevestreza** [comment]
Changes have been merged from wharris/MGTwitterEngine@235d9ad99858a9dc5c17925125206024b9fd862e.
