### ISSUE TITLE
getUserInformationFor: Error with YAJL or TouchJSON

### ISSUE THREAD

**Issue by btjones** [mattgemmell/MGTwitterEngine#31]
When using YAJL or TouchJSON, if getUserInformationFor: is called and the user returned has geolocation information associated with his most recent status, both MGTwitterUsersYAJLParser.m (line 66) and MGTwitterTouchJSONParser.m (line 135) throw an NSInvalidArgumentException because the object being inserted is nil.

I suspect they need to be rewritten in a similar fashion that MGTwitterStatusesYAJLParser was recently rewritten.

**Comment by btjones** [comment]
I have a solution that will work for now. I have created a generic YAJL parser for handling some types of Objects (Users, Statuses, and Direct Messages) - commit here: http://github.com/btjones/MGTwitterEngine/commit/a8cbeb293ee4ec4f05a4d6688e6792c77065f30d

The new generic parser would ideally parse all objects but it is not quite set up for that yet. It has problems with arrays (specifically I was testing with the Trends api which returns an array of trends).

A pull request has been made.

**Comment by stevestreza** [comment]
I merged the generic object parser directly into the MGTwitterYAJLParser, so that it would be easier to make the remaining subclasses work. I put it up in a branch, yajl-generic, in 945314626ed64ba24354da9f44c243b4d969c93b. I'll merge into master once I'm convinced it's stable.

**Comment by stevestreza** [comment]
I fixed the social graph methods in 84aef99edc254c277263a6912201571a49143136.

**Comment by btjones** [comment]
FYI the generic parser does NOT work with array objects like what is returned with search api calls. That's why I didn't implement the generic parser for everything and only implemented it for the items that don't contain arrays. Ideally it would work with arrays and nested arrays but I didn't get to that just yet.

**Comment by CraigMerchant** [comment]
Does anyone know of a good fix for this? When using YAJL getUserInformationFor causes a crash on some users but not others

**\* -[NSMutableArray insertObject:atIndex:]: attempt to insert nil object at 1

I wouldn't bother using YAJL but I need it for trends/search

**Comment by CraigMerchant** [comment]
Hadn't seen the generic branch, works fine with that.

**Comment by btjones** [comment]
Has anyone reviewed the generic YAJL branch to be integrated with the main branch? I think the bug that Hyabusa and I both encountered is a fairly large one.

**Comment by stevestreza** [comment]
The generic YAJL branch _should_ be ready to go, but I haven't checked it lately (I've been caught up in a sudden job change/cross country move, and haven't had time to go through the code). I'll go over it this weekend and merge it in if I don't find any problems.

**Comment by tarasis** [comment]
Whats the status of the Generic branch?

**Comment by btjones** [comment]
@tarasis The last update I heard was in this thread. I haven't made any updates to my branch in a while.
