### ISSUE TITLE
MGTwitterEngine.m compile error

### ISSUE THREAD

**Issue by khakionion** [mattgemmell/MGTwitterEngine#33]
When setting USE_LIBXML=1, MGTwitterEngine.m will not compile. The error is on line 755, specifically the parameter initWithData. The argument being passed is jsonData, but it should be xmlData, because jsonData is #ifdef'd out in this particular use case. 

In my experience, simply setting jsonData to xmlData fixes the compile.

**Comment by stevestreza** [comment]
Fixed in d1829a5380d1e624914e3fc520925da538b9c1e3.
