### ISSUE TITLE
Add support for tagging tweets with location

### ISSUE THREAD

**Issue by stevestreza** [mattgemmell/MGTwitterEngine#4]
Posted tweets cannot be geotagged in the current version.

**Comment by alexrepty** [comment]
Request for review:

http://github.com/alexrepty/MGTwitterEngine/commit/290edc5bf4d9ac9425d44ca418f63f8b9ffeae46

**Comment by stevestreza** [comment]
Along with alexrepty/MGTwitterEngine@a4462b9581fc8a205c66a1a3a4d168c95f59d896 this looks good.

**Comment by alexrepty** [comment]
Yeah, forgot that at first. ctshryock said he'll merge it with his changes over the weekend.

**Comment by alexrepty** [comment]
ctshryock merged and committed these changes, so I guess this can be closed.
