### ISSUE TITLE
Issue when unfollowing

### ISSUE THREAD

**Issue by funkyboy** [mattgemmell/MGTwitterEngine#41]
When I unfollow twitter returns a userInfo that I am still following the user I have just unfollowed.
The opposite (when I follow) works fine.
Any idea?

ps: when I refresh user info is correct. It is wrong only in the callback of the unfollow action.

**Comment by catsby** [comment]
Are you still following that person after you use MGTwitterEngine to un-follow them?  According to the API docs, this call should return the unfollowed user in the requested format when successful.

It seems odd, but that's what it's supposed to do.  Now, if you use MGTwitterEngine to un-follow someone and it returns this userinfo and you find you're still following them, then it's a bug.

See API docs on [friendship/destroy](http://dev.twitter.com/doc/post/friendships/destroy)

**Comment by catsby** [comment]
clarified expected data returned by friendship/destroy

**Comment by funkyboy** [comment]
I think it is a bug. 
Twitter returns that I am still following him/her in the callback of the unfollow. 

Weird is that if I refresh user profile (by calling getUserInformationFor) the info is correct, 
e.g. I am not following him/her

**Comment by catsby** [comment]
So it's a Twitter bug then?  To my knowledge MGTwitterEngine wouldn't be altering the data returned to it before it displays it

**Comment by funkyboy** [comment]
I sent a message to the newsgroup. Hope they reply. 
I also changed the cache policy in the MGTwitterEngine to NSURLRequestReloadIgnoringLocalCacheData but that did not solve

**Comment by catsby** [comment]
I consider this issue closed then, agreed?

**Comment by funkyboy** [comment]
yep. will post news if any.
