### ISSUE TITLE
Favorites returns a 401 code

### ISSUE THREAD

**Issue by funkyboy** [mattgemmell/MGTwitterEngine#42]
Hi,

I am using favorites api.
E.g. /1/favorites/create/21993683042.json

Tested with twurl: twurl -X POST /1/favorites/create/21993683042.json
It works as expected.

The same call on MGTwitterEngine fires a -requestFailed: withError:
Error is: Error Domain=HTTP Code=401 "Operation could not be completed. (HTTP error 401.)
Any idea?

Thanks.

**Comment by catsby** [comment]
401 means the server thinks the call is correct, however authorization was not valid or provided.  

Have you verified your token is correct and set before the call?

**Comment by funkyboy** [comment]
Silly me. Was not setting Access Token. 
Thanks.
