### ISSUE TITLE
Incorrect Format Sequence Used for Tweet IDs

### ISSUE THREAD

**Issue by mattpat** [mattgemmell/MGTwitterEngine#6]
Hey y'all,

On line 1033 of MGTwitterEngine.m (HEAD as of a couple of days ago), `%u` is used to convert the tweet ID into a string. However, the type of the ID (according to the method signature) is `unsigned long`, thus it should be changed to `%lu`.

This was the cause of a bug in Bluebird that stopped the "in reply to" flag from being set on reply tweets. I can only imagine that other devs also experienced this bug, but just silently fixed it themselves and didn't share. _sigh_ :)

-Matt

**Comment by stevestreza** [comment]
In my fork I put the `unsigned long` type into a `MGTwitterEngineID` typedef and a couple utility functions for converting tweet IDs into a string and vice-versa.

**Comment by mattpat** [comment]
Good move, looking forward to the merge. :)

**Comment by alexrepty** [comment]
Matt,

the fix should now be in the repository. Please verify the changes and let us know if anything is still going wrong.

Cheers,
Alex

**Comment by mattpat** [comment]
All looking good to me, I'll post if there are any other issues I run into. :)
