### ISSUE TITLE
Snowflake support

### ISSUE THREAD

**Issue by maddox** [mattgemmell/MGTwitterEngine#66]
I'm pretty sure MGTwitterEngine got 64bit int support for IDs a while ago, but I just wanted to get this answered officially.

Is MGTwitterEngine currently ready for Snowflake 64bit ID support?

**Comment by aral** [comment]
From MGTwitterEngineGlobalHeader:

#define **MGTWITTERENGINEID**
typedef unsigned long long MGTwitterEngineID;
typedef long long MGTwitterEngineCursorID;
