### ISSUE TITLE
Compilation error om MGTwitterGlobalHeader.h

### ISSUE THREAD

**Issue by hakimny** [mattgemmell/MGTwitterEngine#67]
Hi Guys

First of all i would like to thank Matt and all those who contributed to this great product. I have downloaded the project and added teh requested files to my own project but when i build it i receive this error message:
$root/MGTwitterEngine/MGTwitterEngineGlobalHeader.h:76: error: expected '=', ',', ';', 'asm' or '**attribute**' before 'typedef'
# ifndef **MGTWITTERENGINEID**
# define **MGTWITTERENGINEID**

//XCODE Points to the line below when displaying the error
typedef unsigned long long MGTwitterEngineID;
typedef long long MGTwitterEngineCursorID;
# endif

Any help on this is highly appreciated

Thx

**Comment by catsby** [comment]
Your Global header should look like this:
https://github.com/mattgemmell/MGTwitterEngine/blob/master/MGTwitterEngineGlobalHeader.h

The exeptions being if you've set `YAJL_AVAILABLE` or `TOUCHJSON_AVAILABLE`.

I checked out the project from head, added the necessary files, and do not get the same error.
