### ISSUE TITLE
Retweet Support

### ISSUE THREAD

**Issue by justin** [mattgemmell/MGTwitterEngine#8]
Currently can't retweet a tweet using the native retweet support.

This fork has a working version.  I haven't had a chance to go through the code, but linking it as a starting point perhaps.

http://github.com/freeatnet/MGTwitterEngine/commit/294035e5e7cde40c7d0239502ee208d872a6c1f6

**Comment by ghost** [comment]
I added retweet support for my use before I noticed this, but here is my version. It only has support for retweeting, not getting retweets, but it does seem to behave more like a proper MGTwitterEngine citizen.

miketomasello/MGTwitterEngine@16fd160d4a5285ba1d4ded05cf421f6fdf2317c5

**Comment by stevestreza** [comment]
Merged into master.
