### ISSUE TITLE
MGTwitterEngine for send update

### ISSUE THREAD

**Issue by ankurdiyora** [mattgemmell/MGTwitterEngine#81]
Hi,
I have access token, token secret & username. Using that i want to post message(sendUpdate) from iPhone. I am trying to set this parameter in MGTwitterEngine class. But in sendUPdates its gives me error:The operation couldn’t be completed. (HTTP error 401.) 
So how can post message?

Thank you...

**Comment by catsby** [comment]
A 401 error, as defined here ( http://www.checkupdown.com/status/E401.html ) indicates you are not authorized.  

Make sure you've read and completed the steps here: https://dev.twitter.com/pages/xauth

And are familiar with using xauth in MGTwitterEngine, which is described here: 
http://www.2bros1blog.com/2010/07/switching-from-basic-to-xauth-with-mgtwitterengine-on-iphone/
